# Generated by Django 2.2.3 on 2019-07-07 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmediasetting',
            old_name='linedin',
            new_name='linkedin',
        ),
    ]
