# Generated by Django 2.2.2 on 2019-07-06 22:36

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='text',
            field=wagtail.core.fields.StreamField([('text_block', wagtail.core.blocks.StructBlock([('simple_text', wagtail.core.blocks.TextBlock())])), ('heading_block', wagtail.core.blocks.StructBlock([('heading_text', wagtail.core.blocks.CharBlock(classname='title', required=True)), ('size', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('', 'Select a header size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], required=False))])), ('paragraph_block', wagtail.core.blocks.RichTextBlock(icon='fa-paragraph', template='blocks/paragraph_block.html'))], blank=True, verbose_name='Text Body'),
        ),
    ]
