# Generated by Django 2.2.2 on 2019-07-06 23:14

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190706_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='text',
            field=wagtail.core.fields.StreamField([('text_block', wagtail.core.blocks.StructBlock([('simple_text', wagtail.core.blocks.TextBlock())])), ('heading_block', wagtail.core.blocks.StructBlock([('heading_text', wagtail.core.blocks.CharBlock(classname='title', required=True)), ('size', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('', 'Select a header size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], required=False))])), ('paragraph_block', wagtail.core.blocks.RichTextBlock(icon='fa-paragraph', template='blocks/paragraph_block.html')), ('card_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='add your title', required=True)), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(required=False)), ('body', wagtail.core.blocks.RichTextBlock(required=False)), ('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button', wagtail.core.blocks.URLBlock(required=False))])))]))], blank=True, verbose_name='Text Body'),
        ),
    ]
