# Generated by Django 2.2.3 on 2019-07-31 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='SectionTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='section_one',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.SectionOne'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='section_two',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.SectionTwo'),
        ),
    ]
