# Generated by Django 2.2.3 on 2019-08-01 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20190731_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionone',
            name='title',
        ),
        migrations.RemoveField(
            model_name='sectiontwo',
            name='title',
        ),
        migrations.AddField(
            model_name='sectionone',
            name='header',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sectiontwo',
            name='header',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='section_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.SectionOne', unique=True),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='section_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.SectionTwo', unique=True),
        ),
        migrations.AlterField(
            model_name='sectionone',
            name='body',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sectiontwo',
            name='body',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
