# Generated by Django 2.2.3 on 2019-08-02 03:57

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20190801_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPageSections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('header', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='gallerypage',
            name='section_one',
        ),
        migrations.RemoveField(
            model_name='gallerypage',
            name='section_two',
        ),
        migrations.DeleteModel(
            name='SectionOne',
        ),
        migrations.DeleteModel(
            name='SectionTwo',
        ),
        migrations.AddField(
            model_name='gallerypagesections',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_one', to='gallery.GalleryPage'),
        ),
    ]
