# Generated by Django 2.2.3 on 2019-07-17 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20190717_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='left',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='main',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='right',
        ),
    ]
