# Generated by Django 2.2.3 on 2019-07-17 02:49

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_aboutpage_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='cover',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='selection',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(label='Some cool heading')), ('structblock', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('number', wagtail.core.blocks.IntegerBlock()), ('Choice', wagtail.core.blocks.ChoiceBlock(choices=[('tea', 'Tea'), ('coffee', 'Coffee')], icon='cup')), ('document', wagtail.documents.blocks.DocumentChooserBlock()), ('url', wagtail.core.blocks.URLBlock()), ('date', wagtail.core.blocks.DateBlock()), ('time', wagtail.core.blocks.TimeBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True),
        ),
    ]
