# Generated by Django 2.2.3 on 2019-07-04 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190704_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name_plural': 'Home Pages'},
        ),
    ]
