# Generated by Django 2.2.3 on 2019-07-04 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name_plural': 'About Pages'},
        ),
    ]
