# Generated by Django 2.2.3 on 2019-07-04 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20190704_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'About Page', 'verbose_name_plural': 'About Pages'},
        ),
    ]
