# Generated by Django 2.2.3 on 2019-07-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={'verbose_name': 'Blog Page', 'verbose_name_plural': 'Blog Pages'},
        ),
        migrations.AddField(
            model_name='blogpage',
            name='text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
