# Generated by Django 2.2.3 on 2019-07-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190721_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='body',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='head',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
