# Generated by Django 2.2.3 on 2019-07-21 04:14

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_firstsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstsection',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
