# Generated by Django 2.2.3 on 2019-07-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='social_dribbble',
            field=models.BooleanField(default=False, verbose_name='Dribbble'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='social_facebook',
            field=models.BooleanField(default=False, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='social_google_plus',
            field=models.BooleanField(default=False, verbose_name='Google Plus'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='social_instagram',
            field=models.BooleanField(default=False, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='social_linkedin',
            field=models.BooleanField(default=False, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='social_pinterest',
            field=models.BooleanField(default=False, verbose_name='Pinterest'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='social_skype',
            field=models.BooleanField(default=False, verbose_name='Skype'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='social_twitter',
            field=models.BooleanField(default=False, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='social_vimeo',
            field=models.BooleanField(default=False, verbose_name='Vimeo'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='social_youtube',
            field=models.BooleanField(default=False, verbose_name='YouTube'),
        ),
    ]
