# Generated by Django 2.2.3 on 2019-07-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190722_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='social_dribbble',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='social_facebook',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='social_google_plus',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='social_instagram',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='social_linkedin',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='social_pinterest',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='social_skype',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='social_twitter',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='social_vimeo',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='social_youtube',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='open_in_new_tab',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
