# Generated by Django 2.2.3 on 2019-07-22 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('blog', '0008_auto_20190722_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='open_in_new_tab',
            field=models.BooleanField(blank=True, default=False, verbose_name='Example'),
        ),
    ]
